//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadJob.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreadJob.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse script file..
        /// </summary>
        internal static string CannotParseScriptFile {
            get {
                return ResourceManager.GetString("CannotParseScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start job because it is not in NotStarted state..
        /// </summary>
        internal static string CannotStartJob {
            get {
                return ResourceManager.GetString("CannotStartJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path extension.  Extension should be .ps1..
        /// </summary>
        internal static string FilePathExt {
            get {
                return ResourceManager.GetString("FilePathExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath cannot contain wildcards..
        /// </summary>
        internal static string FilePathWildcards {
            get {
                return ResourceManager.GetString("FilePathWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No script block or script file was provided for the job to run..
        /// </summary>
        internal static string NoScriptToRun {
            get {
                return ResourceManager.GetString("NoScriptToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get the value of the Using expression {0}.  Start-ThreadJob only supports using variable expressions..
        /// </summary>
        internal static string UsingNotVariableExpression {
            get {
                return ResourceManager.GetString("UsingNotVariableExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Using variable {0}..
        /// </summary>
        internal static string UsingVariableNotFound {
            get {
                return ResourceManager.GetString("UsingVariableNotFound", resourceCulture);
            }
        }
    }
}
